export const exerciseData = [
  // ─── Chest ──────────────────────────────────────────────────────────
  {
    name: "Barbell Bench Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Incline Dumbbell Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Cable Fly",
    muscleGroups: { primary: ["chest"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Machine Chest Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "machine",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Dumbbell Fly",
    muscleGroups: { primary: ["chest"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Incline Barbell Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Decline Barbell Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Decline Dumbbell Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Pec Deck",
    muscleGroups: { primary: ["chest"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Smith Machine Bench Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "smith_machine",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Low-to-High Cable Fly",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts"] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Dumbbell Squeeze Press",
    muscleGroups: { primary: ["chest"], secondary: ["triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Back ───────────────────────────────────────────────────────────
  {
    name: "Barbell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Pull-Up",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [6, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Seated Cable Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Chest-Supported Dumbbell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "One-Arm Dumbbell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "T-Bar Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Pendlay Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Wide-Grip Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Close-Grip Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Chin-Up",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [6, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Machine Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Chest-Supported Machine Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Cable Pullover",
    muscleGroups: { primary: ["back"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Dumbbell Pullover",
    muscleGroups: { primary: ["back"], secondary: ["chest"] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Meadows Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Quads ──────────────────────────────────────────────────────────
  {
    name: "Barbell Back Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Leg Press",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "machine",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Leg Extension",
    muscleGroups: { primary: ["quads"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Hack Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "machine",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Barbell Front Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes", "abs"] },
    movementPattern: "squat" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Goblet Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Walking Lunge",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Smith Machine Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "smith_machine",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Sissy Squat",
    muscleGroups: { primary: ["quads"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Pendulum Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },

  // ─── Hamstrings ─────────────────────────────────────────────────────
  {
    name: "Romanian Deadlift",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes", "back"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Lying Leg Curl",
    muscleGroups: { primary: ["hamstrings"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Seated Leg Curl",
    muscleGroups: { primary: ["hamstrings"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Dumbbell Romanian Deadlift",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes", "back"] },
    movementPattern: "hip_hinge" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Stiff-Leg Deadlift",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes", "back"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Good Morning",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes", "back"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Single-Leg Romanian Deadlift",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes"] },
    movementPattern: "hip_hinge" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Nordic Hamstring Curl",
    muscleGroups: { primary: ["hamstrings"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Glutes ─────────────────────────────────────────────────────────
  {
    name: "Hip Thrust",
    muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Bulgarian Split Squat",
    muscleGroups: { primary: ["glutes", "quads"], secondary: [] },
    movementPattern: "squat" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Smith Machine Hip Thrust",
    muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
    movementPattern: "hip_hinge" as const,
    equipment: "smith_machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Cable Pull-Through",
    muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
    movementPattern: "hip_hinge" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Glute Bridge",
    muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Cable Kickback",
    muscleGroups: { primary: ["glutes"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Reverse Lunge",
    muscleGroups: { primary: ["glutes", "quads"], secondary: [] },
    movementPattern: "squat" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Machine Hip Abduction",
    muscleGroups: { primary: ["glutes"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Shoulders: Front Delts ─────────────────────────────────────────
  {
    name: "Overhead Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["triceps"] },
    movementPattern: "vertical_press" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Dumbbell Shoulder Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["triceps"] },
    movementPattern: "vertical_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Arnold Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["side_delts", "triceps"] },
    movementPattern: "vertical_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Machine Shoulder Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["triceps"] },
    movementPattern: "vertical_press" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Smith Machine Overhead Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["triceps"] },
    movementPattern: "vertical_press" as const,
    equipment: "smith_machine",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Dumbbell Front Raise",
    muscleGroups: { primary: ["front_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Shoulders: Side Delts ──────────────────────────────────────────
  {
    name: "Dumbbell Lateral Raise",
    muscleGroups: { primary: ["side_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Lateral Raise",
    muscleGroups: { primary: ["side_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Machine Lateral Raise",
    muscleGroups: { primary: ["side_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Y-Raise",
    muscleGroups: { primary: ["side_delts"], secondary: ["rear_delts"] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Dumbbell Upright Row",
    muscleGroups: { primary: ["side_delts"], secondary: ["traps", "front_delts"] },
    movementPattern: "vertical_pull" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Cable Upright Row",
    muscleGroups: { primary: ["side_delts"], secondary: ["traps", "front_delts"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Shoulders: Rear Delts ─────────────────────────────────────────
  {
    name: "Reverse Pec Deck",
    muscleGroups: { primary: ["rear_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Face Pull",
    muscleGroups: { primary: ["rear_delts"], secondary: ["traps"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Dumbbell Reverse Fly",
    muscleGroups: { primary: ["rear_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Reverse Fly",
    muscleGroups: { primary: ["rear_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Incline Dumbbell Reverse Fly",
    muscleGroups: { primary: ["rear_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Biceps ─────────────────────────────────────────────────────────
  {
    name: "Barbell Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Incline Dumbbell Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Hammer Curl",
    muscleGroups: { primary: ["biceps"], secondary: ["forearms"] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "EZ-Bar Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "ez_bar",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Cable Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Preacher Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "ez_bar",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Concentration Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Spider Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Bayesian Cable Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Machine Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Triceps ────────────────────────────────────────────────────────
  {
    name: "Cable Tricep Pushdown",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Overhead Tricep Extension",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Close-Grip Bench Press",
    muscleGroups: { primary: ["triceps"], secondary: ["chest", "front_delts"] },
    movementPattern: "horizontal_press" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Skull Crusher",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "ez_bar",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Dumbbell Overhead Tricep Extension",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Tricep Kickback",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Overhead Tricep Extension",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Machine Tricep Dip",
    muscleGroups: { primary: ["triceps"], secondary: ["chest"] },
    movementPattern: "vertical_press" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Calves ─────────────────────────────────────────────────────────
  {
    name: "Standing Calf Raise",
    muscleGroups: { primary: ["calves"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Seated Calf Raise",
    muscleGroups: { primary: ["calves"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Leg Press Calf Raise",
    muscleGroups: { primary: ["calves"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Smith Machine Calf Raise",
    muscleGroups: { primary: ["calves"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "smith_machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Single-Leg Calf Raise",
    muscleGroups: { primary: ["calves"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Abs ────────────────────────────────────────────────────────────
  {
    name: "Cable Crunch",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Hanging Leg Raise",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Ab Wheel Rollout",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Weighted Decline Crunch",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Machine Crunch",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Pallof Press",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Leg Raise",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Woodchop",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Traps ──────────────────────────────────────────────────────────
  {
    name: "Barbell Shrug",
    muscleGroups: { primary: ["traps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Dumbbell Shrug",
    muscleGroups: { primary: ["traps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Cable Shrug",
    muscleGroups: { primary: ["traps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Smith Machine Shrug",
    muscleGroups: { primary: ["traps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "smith_machine",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Forearms ───────────────────────────────────────────────────────
  {
    name: "Barbell Wrist Curl",
    muscleGroups: { primary: ["forearms"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "barbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [15, 25] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Barbell Reverse Wrist Curl",
    muscleGroups: { primary: ["forearms"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "barbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [15, 25] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Dumbbell Wrist Curl",
    muscleGroups: { primary: ["forearms"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [15, 25] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Reverse Barbell Curl",
    muscleGroups: { primary: ["forearms"], secondary: ["biceps"] },
    movementPattern: "isolation" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Compound Extras ───────────────────────────────────────────────
  {
    name: "Conventional Deadlift",
    muscleGroups: { primary: ["back", "hamstrings"], secondary: ["glutes", "traps", "forearms"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 240,
  },
  {
    name: "Dip",
    muscleGroups: { primary: ["chest", "triceps"], secondary: ["front_delts"] },
    movementPattern: "vertical_press" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [6, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Farmer's Walk",
    muscleGroups: { primary: ["traps", "forearms"], secondary: ["abs"] },
    movementPattern: "carry" as const,
    equipment: "dumbbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [30, 60] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Sumo Deadlift",
    muscleGroups: { primary: ["quads", "glutes"], secondary: ["back", "hamstrings", "forearms"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 240,
  },
  {
    name: "Trap Bar Deadlift",
    muscleGroups: { primary: ["quads", "back"], secondary: ["glutes", "hamstrings", "traps", "forearms"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [5, 8] as [number, number],
    defaultRestSeconds: 240,
  },
  {
    name: "Kettlebell Swing",
    muscleGroups: { primary: ["glutes", "hamstrings"], secondary: ["back", "abs"] },
    movementPattern: "hip_hinge" as const,
    equipment: "kettlebell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Barbell Upright Row",
    muscleGroups: { primary: ["side_delts", "traps"], secondary: ["front_delts", "biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Landmine Press",
    muscleGroups: { primary: ["chest", "front_delts"], secondary: ["triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Weighted Dip",
    muscleGroups: { primary: ["chest", "triceps"], secondary: ["front_delts"] },
    movementPattern: "vertical_press" as const,
    equipment: "bodyweight",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Weighted Pull-Up",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "bodyweight",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Weighted Chin-Up",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "bodyweight",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Push-Up",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "bodyweight",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Inverted Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "bodyweight",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Kettlebell Goblet Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes", "abs"] },
    movementPattern: "squat" as const,
    equipment: "kettlebell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Suitcase Carry",
    muscleGroups: { primary: ["abs", "forearms"], secondary: ["traps"] },
    movementPattern: "carry" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [30, 60] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Additional Chest ───────────────────────────────────────────────
  {
    name: "Flat Dumbbell Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Incline Smith Machine Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "smith_machine",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "High-to-Low Cable Fly",
    muscleGroups: { primary: ["chest"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Incline Machine Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Additional Back ────────────────────────────────────────────────
  {
    name: "Single-Arm Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Straight-Arm Pulldown",
    muscleGroups: { primary: ["back"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [12, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Landmine Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Chest-Supported T-Bar Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Neutral-Grip Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Seal Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Additional Quads ───────────────────────────────────────────────
  {
    name: "Belt Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Step-Up",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "V-Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },

  // ─── Additional Hamstrings ──────────────────────────────────────────
  {
    name: "Cable Romanian Deadlift",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes"] },
    movementPattern: "hip_hinge" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Glute-Ham Raise",
    muscleGroups: { primary: ["hamstrings"], secondary: ["glutes"] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 120,
  },

  // ─── Additional Glutes ─────────────────────────────────────────────
  {
    name: "Dumbbell Hip Thrust",
    muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
    movementPattern: "hip_hinge" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Curtsy Lunge",
    muscleGroups: { primary: ["glutes"], secondary: ["quads"] },
    movementPattern: "squat" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Cable Hip Extension",
    muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Additional Shoulders ──────────────────────────────────────────
  {
    name: "Seated Dumbbell Shoulder Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["triceps"] },
    movementPattern: "vertical_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Behind-the-Neck Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "vertical_pull" as const,
    equipment: "cable",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Prone Incline Y-Raise",
    muscleGroups: { primary: ["rear_delts"], secondary: ["traps"] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Lu Raise",
    muscleGroups: { primary: ["side_delts"], secondary: ["front_delts"] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Additional Biceps ─────────────────────────────────────────────
  {
    name: "Cross-Body Hammer Curl",
    muscleGroups: { primary: ["biceps"], secondary: ["forearms"] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Hammer Curl",
    muscleGroups: { primary: ["biceps"], secondary: ["forearms"] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Dumbbell Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Additional Triceps ────────────────────────────────────────────
  {
    name: "EZ-Bar Overhead Extension",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "ez_bar",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Diamond Push-Up",
    muscleGroups: { primary: ["triceps"], secondary: ["chest"] },
    movementPattern: "horizontal_press" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 15] as [number, number],
    defaultRestSeconds: 90,
  },

  // ─── Additional Abs ─────────────────────────────────────────────────
  {
    name: "Dragon Flag",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [5, 10] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Dead Bug",
    muscleGroups: { primary: ["abs"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },

  // ─── Additional Compound / Miscellaneous ───────────────────────────
  {
    name: "Rack Pull",
    muscleGroups: { primary: ["back"], secondary: ["traps", "glutes", "forearms"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 240,
  },
  {
    name: "Deficit Deadlift",
    muscleGroups: { primary: ["back", "hamstrings"], secondary: ["glutes", "quads"] },
    movementPattern: "hip_hinge" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [4, 8] as [number, number],
    defaultRestSeconds: 240,
  },
  {
    name: "Barbell Hack Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
    movementPattern: "squat" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Zercher Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes", "abs", "back"] },
    movementPattern: "squat" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Safety Bar Squat",
    muscleGroups: { primary: ["quads"], secondary: ["glutes", "back"] },
    movementPattern: "squat" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 180,
  },
  {
    name: "Overhead Carry",
    muscleGroups: { primary: ["abs", "front_delts"], secondary: ["traps"] },
    movementPattern: "carry" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [30, 60] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Kettlebell Clean and Press",
    muscleGroups: { primary: ["front_delts"], secondary: ["triceps", "abs"] },
    movementPattern: "vertical_press" as const,
    equipment: "kettlebell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Plate Front Raise",
    muscleGroups: { primary: ["front_delts"], secondary: ["abs"] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Front Raise",
    muscleGroups: { primary: ["front_delts"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 15] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Cable Face Pull with External Rotation",
    muscleGroups: { primary: ["rear_delts"], secondary: ["traps"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [12, 20] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Band Pull-Apart",
    muscleGroups: { primary: ["rear_delts"], secondary: ["traps"] },
    movementPattern: "isolation" as const,
    equipment: "bodyweight",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [15, 25] as [number, number],
    defaultRestSeconds: 60,
  },
  {
    name: "Single-Arm Cable Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Incline Dumbbell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps", "rear_delts"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "dumbbell",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Machine Pullover",
    muscleGroups: { primary: ["back"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Smith Machine Incline Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "smith_machine",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Incline Cable Fly",
    muscleGroups: { primary: ["chest"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Single-Arm Dumbbell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Kettlebell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "kettlebell",
    sfrRating: "medium",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Dumbbell Bench Press",
    muscleGroups: { primary: ["chest"], secondary: ["front_delts", "triceps"] },
    movementPattern: "horizontal_press" as const,
    equipment: "dumbbell",
    sfrRating: "medium",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Cable Crossover",
    muscleGroups: { primary: ["chest"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Reverse Grip Barbell Row",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "horizontal_pull" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: false,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Machine Lat Pulldown",
    muscleGroups: { primary: ["back"], secondary: ["biceps"] },
    movementPattern: "vertical_pull" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [8, 12] as [number, number],
    defaultRestSeconds: 120,
  },
  {
    name: "Lying Cable Curl",
    muscleGroups: { primary: ["biceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "Rope Pushdown",
    muscleGroups: { primary: ["triceps"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "cable",
    sfrRating: "high",
    isStretchFocused: false,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 90,
  },
  {
    name: "JM Press",
    muscleGroups: { primary: ["triceps"], secondary: ["chest"] },
    movementPattern: "horizontal_press" as const,
    equipment: "barbell",
    sfrRating: "low",
    isStretchFocused: true,
    repRangeOptimal: [6, 10] as [number, number],
    defaultRestSeconds: 150,
  },
  {
    name: "Donkey Calf Raise",
    muscleGroups: { primary: ["calves"], secondary: [] },
    movementPattern: "isolation" as const,
    equipment: "machine",
    sfrRating: "high",
    isStretchFocused: true,
    repRangeOptimal: [10, 15] as [number, number],
    defaultRestSeconds: 60,
  },
];
